### ISSUE TITLE
Fix tests for where registers are mapped to SRAM

### ISSUE THREAD

**Issue by Jordin089** [Flu/avr-emulator#30]
currently there are 3 tests which do not work on the "feature/8-map-registers-to-sram" branch.
(this branch might soon after writing this be merged so make sure t take that into account)

these need to be changed in order to not reach memory locations outside of the size of the memory.
Some tests also attempt to use registers which are not labelled between 0-31 (since some currently attempt to access registers with higher indexes (i.e. R35) which do not exist and thus return an error).

**Comment by Flu** [comment]
Issue closed, since #31 is also closed
